### ISSUE TITLE
Both the Docker and Standalone installation instructions are broken

### ISSUE THREAD

**Issue by PCSmith** [tootsuite/documentation#413]
For me the standalone steps resulted in errors about a version issue with ruby and the docker wouldnt even let me clone the repo due to some permissions issue. I'd love to set up a node for a bunch of interested people but I'll need a resource that can get me through it. Thanks for your help.

**Comment by PCSmith** [comment]
Here's a specific issue... Standalone instructions....

You have me installing "rbenv install 2.4.2" but the following command returns an error.

gem install bundler
rbenv: version `2.4.1' is not installed (set by /home/mastodon/live/.ruby-version)

I updated the .ruby-version file to reflect 2.4.2 to see if that would allow me to continue.

**Comment by PCSmith** [comment]
Need instructions on what to do with these... They are vague and I guess assume experience with this tool.

# Application secrets
# Generate each with `RAILS_ENV=production bundle exec rake secret`
PAPERCLIP_SECRET=
SECRET_KEY_BASE=
OTP_SECRET=

# Web Push VAPID keys
# Generate with `RAILS_ENV=production bundle exec rake mastodon:webpush:generate_vapid_key`
VAPID_PRIVATE_KEY=
VAPID_PUBLIC_KEY=

**Comment by PCSmith** [comment]
Running RAILS_ENV=production bundle exec rake secret and RAILS_ENV=production bundle exec rake mastodon:webpush:generate_vapid_key are insufficient to continue on with RAILS_ENV=production bundle exec rails db:setup as the error seems to indicate it's missing a key thats probably generated with the above.

"rails aborted!
Devise.secret_key was not set."

**Comment by khakist** [comment]
For "RAILS_ENV=production bundle exec rake secret", you need to run that three times.  You'll get three different values.  Cut and paste into each of the three blank fields.  

For "RAILS_ENV=production bundle exec rake mastodon:webpush:generate_vapid_key" you just need to run it once; it'll give you both a private and a public key.  

For both commands, it probably helps for you to open a separate terminal window.

But the install instructions are still broken.  You need to run "RAILS_ENV=production bundle exec rails webpacker:install" before you run "RAILS_ENV=production bundle exec rails assets:precompile".  Even then, I'm still getting compilation errors that don't make sense.

**Comment by Starling000** [comment]
This is still an issue. The guide assumes a lot of the reader and is missing critical steps. I haven't been able to get even a single user instance working using these guides.

**Comment by coreyreichle** [comment]
In fairness, the guide does presume a skilled linux administrator, and I believe states as much.

I can "fix" the documentation there.  I know the vapid key run needs to happen after the rest of the conf file is done, and written.  Without the other secrets, it wont run.

As for ruby versions, that's an easy fix (Change the gemspec line in the guide).  Again, I can do a PR for this change.

**Comment by corbindavenport** [comment]
Yeah, I'm stuck in this part of the documentation instead. Generating the keys doesn't work, and running `RAILS_ENV=production bundle exec rails db:setup` gives me this:

````
mastodon@localhost:~/live$ RAILS_ENV=production bundle exec rails db:setup
Created database 'mastodon_production'
rails aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = '123456'

Please ensure you restarted your application after installing Devise or setting the key.
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/devise-4.3.0/lib/devise/rails/routes.rb:498:in `raise_no_secret_key'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/devise-4.3.0/lib/devise/rails/routes.rb:226:in `devise_for'
/home/mastodon/live/config/routes.rb:29:in `block in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:408:in `draw'
/home/mastodon/live/config/routes.rb:8:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:55:in `block in load_paths'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:55:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:55:in `load_paths'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:18:in `reload!'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:41:in `block in updater'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/file_update_checker.rb:81:in `execute'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:42:in `updater'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:31:in `execute_if_updated'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:128:in `block in <module:Finisher>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/home/mastodon/live/config/environment.rb:5:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)

````

**Comment by corbindavenport** [comment]
I followed the advice of @khakist about generating the keys, but running the precompile command fails:

````
mastodon@localhost:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
Webpacker is installed 🎉 🍰
Using /home/mastodon/live/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:

module.js:471
    throw err;
    ^

Error: Cannot find module '../lib/install/config/webpacker.yml'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (/home/mastodon/live/node_modules/@rails/webpacker/package/config.js:6:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

mastodon@localhost:~/live$ Error: Cannot find module '../lib/install/config/webpacker.yml'
````
