### ISSUE TITLE
[bug] rake command make_admin is not working

### ISSUE THREAD

**Issue by albjeremias** [tootsuite/documentation#644]
When i run 
```bash
$ docker-compose run --rm web rake --trace mastodon:make_admin USERNAME=user
``` 
output:
```bash
WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
pip uninstall docker-py; pip uninstall docker; pip install docker
Starting mastodon_db_1 ... 
Starting mastodon_redis_1 ... done
rake aborted!
Gem::LoadError: You have already activated rake 12.0.0, but your Gemfile requires rake 12.3.1. Prepending `bundle exec` to your command may solve this.
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:313:in `check_for_activated_spec!'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:31:in `block in setup'
/usr/local/lib/ruby/2.4.0/forwardable.rb:229:in `each'
/usr/local/lib/ruby/2.4.0/forwardable.rb:229:in `each'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:26:in `map'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:26:in `setup'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler.rb:107:in `setup'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/setup.rb:10:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/mastodon/config/boot.rb:3:in `<top (required)>'
/mastodon/config/application.rb:1:in `require_relative'
/mastodon/config/application.rb:1:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/mastodon/Rakefile:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

I'm runnning mastodon gargron/mastodon:v2.4.2 ...

I expect the user to be admin of the instance

**Comment by andi1984** [comment]
Same issue here:

```
Starting mastodon_redis_1 ... done
Starting mastodon_db_1    ... done
rake aborted!
Don't know how to build task 'mastodon:make_admin' (see --tasks)
Did you mean?  mastodon:stats
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/task_manager.rb:59:in `[]'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:159:in `invoke_task'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/bin/rake:23:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli.rb:424:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/exe/bundle:22:in `<top (required)>'
/mastodon/bin/bundle:3:in `load'
/mastodon/bin/bundle:3:in `<main>'
```

**Comment by andi1984** [comment]
@albjeremias I found my issue: make_admin moved to tootctl.
